# Generated by Django 4.1 on 2025-02-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="researcher_form",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_Name", models.CharField(max_length=100)),
                ("last_Name", models.CharField(max_length=100)),
                ("current_project", models.CharField(max_length=100)),
                ("uv_name", models.CharField(max_length=100)),
                ("dept_name", models.CharField(max_length=100)),
                ("session", models.CharField(max_length=100)),
                ("interested_domain", models.CharField(max_length=200)),
                ("experiences", models.CharField(max_length=200)),
                (
                    "num_stars",
                    models.IntegerField(
                        choices=[
                            (1, "Active"),
                            (2, "Very Active"),
                            (3, "Hardworking"),
                            (4, "Excellent Hardworking"),
                            (5, "Extraordinary"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="researcher_recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Details", models.CharField(max_length=300)),
                (
                    "researcher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Researchers.researcher_form",
                    ),
                ),
            ],
        ),
    ]
