# Generated by Django 4.1 on 2025-02-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Researchers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="researcher_form",
            old_name="num_stars",
            new_name="Ranking",
        ),
    ]
