# Generated by Django 4.1 on 2025-02-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Researchers", "0002_rename_num_stars_researcher_form_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher_form",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="researcher_form",
            name="linekdin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="researcher_form",
            name="personal_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="researcher_form",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="researcher_form",
            name="Ranking",
            field=models.IntegerField(default=60),
        ),
    ]
