# Generated by Django 4.1 on 2025-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Researchers", "0003_researcher_form_github_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher_form",
            name="google_scholar_url",
            field=models.URLField(blank=True),
        ),
    ]
