# Generated by Django 4.1 on 2025-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("paper_title", models.CharField(max_length=100)),
                (
                    "publication_pics",
                    models.ImageField(blank=True, upload_to="publication_pics/"),
                ),
                ("Publication_details", models.CharField(max_length=500)),
                ("publication_url", models.URLField()),
            ],
        ),
    ]
