# Generated by Django 4.1 on 2025-02-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PublicationProject", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="publication_pics",
            new_name="publication_pic",
        ),
    ]
