# Generated by Django 4.1 on 2025-02-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PublicationProject",
            "0002_rename_publication_pics_publication_publication_pic",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_title", models.CharField(max_length=100)),
                (
                    "project_pic",
                    models.ImageField(blank=True, upload_to="project_pics/"),
                ),
                ("Githuv_url", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="publication",
            name="Publication_details",
        ),
    ]
