# Generated by Django 4.1 on 2025-02-20 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered in digits only.", regex="^\\d+$"
                    )
                ],
            ),
        ),
    ]
