# Generated by Django 4.1 on 2025-02-23 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0003_userinfo_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
