# Generated by Django 4.1 on 2025-02-23 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0004_userinfo_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
